### ISSUE TITLE
Machines causing crashes

### ISSUE THREAD

**Issue by Fragilityx** [IsotopeReal/MkPlus#1]
I tried to use smelters and they crashed the game as soon as they received an input. I reloaded and tested constructors as well, same result. I made a new mod profile running only MkPlus and the result is still the same.

**Comment by realisotope** [comment]
Thanks for the report and test. I have found the issue and pushed an update to smm, please let me know if you experience any more crashes.
also working on an issue with some extra pipes.

sorry for any inconvenience.

**Comment by Fragilityx** [comment]
The constructor is still causing crashes for me. The smelter and assembler appear to be fine. I'll try other machines to see if the issue is still present.

**Comment by Fragilityx** [comment]
Constructors are fixed in 1.0.2, thanks! Unless I missed something, it seems most things are working. No crashes yet.
