### ISSUE TITLE
Missing source code

### ISSUE THREAD

**Issue by budak7273** [IsotopeReal/MkPlus#4]
This repository appears to be just a readme. You can find a detailed guide on setting up Git with your Unreal Editor here: https://docs.ficsit.app/satisfactory-modding/latest/Development/BeginnersGuide/CreateGitRepo.html

If this repo is intentionally just for issue tracking and not code, you should probably mention that in the readme or a CONTRIBUTING.md

**Comment by realisotope** [comment]
i've pushed the source 👍
