### ISSUE TITLE
Blender Mk3 not fully functioning

### ISSUE THREAD

**Issue by Ghost47Killer** [IsotopeReal/MkPlus#6]
Version 1.0.5, blender Mk3 just using one output

![20241108223948_1](https://github.com/user-attachments/assets/f59027af-5bb1-4c3c-b7b7-8402976d2425)
![20241108223945_1](https://github.com/user-attachments/assets/02cd0717-3973-4734-9887-456de7c886d4)
![20241108223942_1](https://github.com/user-attachments/assets/d312f65a-2765-4868-a9a4-5db4ad386a56)
![20241108223939_1](https://github.com/user-attachments/assets/cbda22ff-53c1-4888-9ed3-78d62a6ccfe0)
![20241108223935_1](https://github.com/user-attachments/assets/928c14c2-66ec-43b5-a99e-54ae31fb9013)

**Comment by realisotope** [comment]
Hi Ghost. as stated on the MkPlus mod page, the extra pipes on the blender/packager are currently not working. i'm still working to fix them but it's more complicated than the belts since the 1.0 update. sorry for any inconvenience

**Comment by Ghost47Killer** [comment]
oh, I'm sorry man, but thanks for the hard work, this mod it's awesome!!!

**Comment by Ghost47Killer** [comment]
Do you want me to keep this post or just close it?
